### ISSUE TITLE
Wrong README examples

### ISSUE THREAD

**Issue by vptcnt** [SethuSenthil/is-pirated#1] opened 2021-04-19 11:24 UTC
Hello,

Just to tell you that the README shows wrong info 

print(isPirated.status);
// true - (iOS) if installed from AppStore or TestFlight, (Android) if installed from PlayStore
// false - if installed without authorization or receipt (Via ABD, APK, IPA)

Compared to the source code 

bool isItPirated = false;
//Return True if installed WITHOUT proper store autherositaion
//Retuns False if installed through proper app store

I guess false and true should be swapped.

**Comment by SethuSenthil** [comment] 2021-04-19 12:30
Thanks for opening an issue! It's been fixed in the latest push!

**Closed as completed** 2021-04-19 12:29 UTC

**Comment by HamzaMihfad** [comment] 2021-12-20 16:51
@SethuSenthil  the issue is still there, false and true should be swapped.
